Use typescript@4.3 and ts-node@10.1
OfficeDev/Office-Addin-Scripts pull request #492
Opened 2021-07-14 18:56 UTC by jozefizso

2021-07-14 19:19 UTC, akrantz approved these changes
Thanks for the PR! This looks good. I made one suggestion about a code change.

2021-07-14 19:19 UTC, akrantz commented on packages/custom-functions-metadata/src/generate.ts
> -  return tag && tag.comment ? tag.comment : "";
Could this be updated to `return tag?.comment?.toString() || ""` ?  Do you think it is better that way?

2021-07-14 19:20 UTC, akrantz requested changes
Seems like it's better for me to mark this as request changes. Mention me if you make an update or if you don't want to, and I can follow up then.

2021-07-19 09:13 UTC, jozefizso commented
@akrantz I change the code as requested.

2021-07-19 12:20 UTC, akrantz approved these changes

2021-07-19 12:20 UTC, merged