Making export code await to zip be created
OfficeDev/Office-Addin-Scripts pull request #582
Opened 2022-01-13 20:23 UTC by igor-ribeiiro

Tests for the manifest export function were flaky because the function did not wait for the zip file to be created.
Fixed it so the code is more consistent.

2022-01-13 20:31 UTC, millerds commented
Can you explain a little more?  The function was synchronous so it should have been waiting already . . . I'm not sure how making it async makes it wait?

2022-01-13 20:36 UTC, igor-ribeiiro commented
> Can you explain a little more? The function was synchronous so it should have been waiting already . . . I'm not sure how making it async makes it wait?

When executing the tests on master the functions would sometimes pass and sometimes not. After playing a while with some "sleep" functions, I noticed it was a problem that the zip stream isn't really sync.
It relies on this `.on("finish")` in order to actually wait for it to finish.

2022-01-13 21:09 UTC, akrantz commented
This makes sense to me.

2022-01-13 21:09 UTC, akrantz approved these changes

2022-01-14 00:00 UTC, millerds requested changes
I you are doing an await on the new promise inside the function do we need to make the function itself async and return a promise or is that inner await sufficient?

2022-01-14 00:07 UTC, igor-ribeiiro commented on packages/office-addin-manifest/src/export.ts
> +export async function exportMetadataPackage(
To use await we do need to make the function async and return promises. It is all linked together

2022-01-14 00:11 UTC, igor-ribeiiro commented on packages/office-addin-manifest/src/export.ts
> +export async function exportMetadataPackage(
For example, by using await on a non async function I get: 
"'await' expressions are only allowed within async functions and at the top-level modules". And an Async functions needs to return a promise

2022-01-14 00:38 UTC, millerds approved these changes

2022-01-14 00:47 UTC, merged