[minor] Add @capturesCallingObject tag handling
OfficeDev/Office-Addin-Scripts pull request #883
Opened 2024-08-15 22:13 UTC by legutieMSFT

Thank you for your pull request!  

Please add '[major]', '[minor]', or [patch] to the title to indicate the impact the change has on the code.  Please also provide the following information.

---

**Change Description**:

    Handle @capturesCallingObject metadata tag for Excel javascript custom functions

1. **Do these changes impact *command syntax* of any of the packages?** (e.g., add/remove command, add/remove a command parameter, or update required parameters)
    No

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins)
    Yes, but will be handled separately to indicate what the flag means

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

**Validation/testing performed**:

    Will validate it works with scriptlab in excel

2024-08-15 22:34 UTC, legutieMSFT commented
> @microsoft-github-policy-service agree company="Microsoft"

@microsoft-github-policy-service agree company="Microsoft"

2024-08-15 23:01 UTC, jeaniehuynh approved these changes

2024-08-16 00:35 UTC, rdong999 commented on packages/custom-functions-metadata/Specification.md
> +This tag is required to generate metadata for the custom function.
Please improve the wording for "This tag is required to generate metadata for the custom function."

2024-08-16 00:36 UTC, rdong999 commented on packages/custom-functions-metadata/test/cases/error-linkedentitydataprovider-capturesCallingObject/functions.js
> + * Test the linkedEntityDataProvider tag in combination with the volatile tag
nit: Please change volatile to capturesCallingObject

2024-08-16 00:38 UTC, rdong999 approved these changes

2024-08-16 01:24 UTC, akrantz requested changes
Generally this looks good, but made some suggestions about spec updates. I also feel like it should validate that the first parameter type is correct for the calling object.

2024-08-16 17:08 UTC, legutieMSFT commented on packages/custom-functions-metadata/test/cases/capturesCallingObject/expected.json
> +                    "type": "any"
I'm adding validation for 1 required, scalar and non-repeating parameter. Will push once that is done

2024-08-16 21:54 UTC, akrantz submitted a review, later dismissed
Looks good now. Thanks for making the updates.

As we discussed, there will be minimum validation for now, and we will discuss about improving that in the future.

2024-08-16 22:15 UTC, jeaniehuynh approved these changes

2024-08-16 22:17 UTC, rdong999 approved these changes

2024-08-19 07:35 UTC, MiaofeiWang approved these changes

2024-08-19 16:42 UTC, Adrian-MSFT approved these changes

2024-08-29 00:33 UTC, akrantz commented
I will approve to unblock this PR. There's still an opportunity to help the developer by validating that they have a parameter for the calling object and it is of an appropriate type.

2024-08-29 00:33 UTC, akrantz approved these changes

2024-09-04 18:40 UTC, merged