Enable parse @requiresAddress and @requiresParameterAddresses together with @streaming for custom functions
OfficeDev/Office-Addin-Scripts pull request #911
Opened 2024-12-04 09:05 UTC by sunyao-ms

**Change Description**:

 
This PR containing the following change:   
1. Enable parse @requiresAddress and @requiresParameterAddresses together with @streaming for custom functions
2. Add unit test

1. **Do these changes impact *command syntax* of any of the packages?** (e.g., add/remove command, add/remove a command parameter, or update required parameters)
    No

3. **Do these changes impact *documentation*?** (e.g., a tutorial on https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins)
    Yes, we will introduce new properties for custom functions, so the doc on https://learn.microsoft.com/en-us/javascript/api/custom-functions-runtime/customfunctions.streaminginvocation?view=excel-js-preview should be updated with how to use the new tags.

**Validation/testing performed**:

    Local unit test pass.

2024-12-04 18:52 UTC, akrantz commented
I think this can be simplified so that the JSDoc tags are the same for streaming and non-streaming functions, e.g. `@requiresParameterAddress`. When the metadata is written out, it can determine whether it is a streaming function or not and can update the metadata appropriately. This way the developer has the same experience adding `@requiresParameterAddress` whether it is streaming or not, and there is an implementation detail that the metadata info is different due to the need to support backward compatibility.

2024-12-04 18:53 UTC, akrantz requested changes
See previous comment

2024-12-04 19:06 UTC, akrantz reviewed
OK, this is good. I have some suggestions for the test cases to update the test case names for consistency.

Is there an error test case when you have these tags but are missing the invocation parameter? It would be good to have that since putting one of these tags should require the invocation parameter which then provides the address / parameter addresses.

2024-12-04 19:06 UTC, akrantz commented on packages/custom-functions-metadata/test/cases/requiresstreamaddress/expected.json
> +{
Please call this requiresaddress-streaming (which is converted from error-requiresaddress-streaming), or consider merging both non-streaming and streaming cases into single requiresaddress test case.

2024-12-04 19:06 UTC, akrantz commented on packages/custom-functions-metadata/test/cases/requiresstreamparameteraddresses/expected.json
> +    "allowCustomDataForDataTypeAny": true,
Let's name this test case requiresparameteraddress-streaming. This is consistent with other test cases in having the tag name first and the variant after the hyphen.

2024-12-05 06:56 UTC, sunyao-ms commented
> OK, this is good. I have some suggestions for the test cases to update the test case names for consistency.
> 
> Is there an error test case when you have these tags but are missing the invocation parameter? It would be good to have that since putting one of these tags should require the invocation parameter which then provides the address / parameter addresses.

I have added the missing invocation test case.

2024-12-05 16:14 UTC, akrantz approved these changes
Thanks for making the updates!

2024-12-05 17:18 UTC, millerds commented
/azurepipelines run

2024-12-05 17:44 UTC, merged